#!/usr/bin/env bash

set -x

if [[ -z "$1" ]]; then
  echo "Usage: [year] <day>"
  exit 1
fi

if [[ -z "$2" ]]; then
  YEAR=twentytwo
  DAY="$1"
else
  YEAR="$1"
  DAY="$2"
fi

if ! grep -q "object $YEAR " build.sc; then
  echo "First, set up module for year $YEAR"
  exit 2
fi

LOC="$YEAR"/"$DAY"/src/"$YEAR"/"$DAY"

mkdir -p "$LOC"
> "$LOC"/"${YEAR^}${DAY^}".scala cat <<EOF
package $YEAR.$DAY

import lib.Support

object ${YEAR^}${DAY^} extends App with Support {
  val i = load

  println(i)
}
EOF

mkdir -p "$YEAR"/"$DAY"/resources
> "$YEAR"/"$DAY"/resources/input.txt cat <<EOF
hello world
EOF

gawk -i inplace -v x="  object $DAY extends ScalaModule with Common" "/object[[:space:]]+$YEAR"'([[:space:]]|[[:alnum:]])+\{/{f=1} !/}/{print} /}/{if (f) print x; print "}"; f=0}' build.sc

./idea

mill "$YEAR.$DAY.run"
